### ISSUE TITLE
Not working in ember-cli 2.13

### ISSUE THREAD

**Issue by snaketoo** [kaliber5/ember-sticky-element#13]

**Comment by snaketoo** [comment]
A component or helper named "sticky-element" could not be found

**Comment by simonihmig** [comment]
Which version of Ember? Also 2.13?

Anything special happening in your app? I have my doubts that there is really a problem here, as the addon does not really do any fancy things that could explain the error you are seeing, and is well tested in all Ember LTS and all current/beta versions.

If you can show a minimal reproduction (like a repo with a fresh app including this addon, that reproduces the error), I am happy to dig into it!

**Comment by simonihmig** [comment]
Was able to reproduce, will dig into it...

**Comment by brunorios1** [comment]
Same here.

ember-cli 2.15.1

Thanks.

**Comment by simonihmig** [comment]
Uh, wow. This was weird. Actually nothing is wrong with the code here, and the issue is also not related to any ember-cli/ember version...

I published this using `yarn publish`, and all the component files were missing from the uploaded tarball! 😱  Just double checked with `yarn pack`, still all those files were missing in the resulting archive! 

Obviously seems to be a bug with `yarn`, will have to report that. Just republished this (using plain old `npm` 😉) as 0.1.5, should work now again with that version!

**Comment by simonihmig** [comment]
For the record: https://github.com/yarnpkg/yarn/issues/4784
