### ISSUE TITLE
Support re-sticking to top on scroll up after sticking to bottom

### ISSUE THREAD

**Issue by kevinansfield** [kaliber5/ember-sticky-element#45]
When a `bottom=0` param is provided so that the element sticks to the bottom of the container, once it's stuck to the bottom it stays there until you scroll back above the container then back down again.

I was expecting the `position: sticky` behaviour to be reapplied when scrolling up past the stuck element so that it's always sitting in the top-left for example.

I made a quick screen recording as it's probably easier to explain that way!
https://youtu.be/yawUVyJmV90

**Comment by simonihmig** [comment]
Thanks for reporting! Indeed that behavior seems wrong. It does not happen on the [demo page](https://kaliber5.github.io/ember-sticky-element/), and the tests are covering this. But maybe this is some edge, maybe because the sticky element is rather small...

Is the demo from the screen recording public? So I get a reliable reproduction?

**Comment by kevinansfield** [comment]
🎉 thank you! Sorry for not getting back regarding the demo, end-of-sprint hustle got in the way. Testing the fixed version out now 😄

**Comment by simonihmig** [comment]
@kevinansfield np! I wanted to publish this version today, but if you are able to test it with the master branch before that, to make sure it really fixes your problem, that would be awesome!

**Comment by kevinansfield** [comment]
👍 tested with the master branch and it's working well

**Comment by simonihmig** [comment]
Thanks! Just published as 0.2.1.
